working_dir: &working_dir ~/app

.build_template: &build_definition
  steps:
    - checkout
    - run: gem install bundler:2.1.4
    - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
    - run: bundle exec rake rubocop
    - run:
        name: Run tests
        command: |
          bundle exec rspec
  working_directory: *working_dir

version: 2.0

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
  build_ruby2_7:
    <<: *build_definition
    docker:
      - image: ruby:2.7
  build_ruby2_6:
    <<: *build_definition
    docker:
      - image: ruby:2.6
  build_ruby2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build
      - build_ruby2_7
      - build_ruby2_6
      - build_ruby2_5
